spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.89.20:3306/esearch?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: lw091211

server:
  port: 8080
  servlet:
    context-path: /esearch



mybatis:
  mapper-locations: com/yangyu/esearch/mapper/*.xml
